import { writeFileSync } from 'node:fs'
import { startWorker } from './fake-worker.ts'

const worker = await startWorker()
const endpoint = `${worker.url}/a2a/jsonrpc`
const out: Record<string, unknown> = {}

async function card(name: string, version: '1.0' | '0.3') {
  const headers: Record<string, string> = version === '1.0' ? { 'A2A-Version': '1.0' } : {}
  out[name] = await (await fetch(`${worker.url}/.well-known/agent-card.json`, { headers })).json()
}

async function rpc(name: string, version: '1.0' | '0.3', method: string, params: unknown) {
  const headers: Record<string, string> = { 'content-type': 'application/json', ...(version === '1.0' ? { 'A2A-Version': '1.0' } : {}) }
  const res = await fetch(endpoint, { method: 'POST', headers, body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }) })
  const body = await res.json()
  out[name] = body
  return body as { result?: any }
}

const v1msg = (text: string) => ({ message: { messageId: crypto.randomUUID(), role: 'ROLE_USER', parts: [{ text }] }, configuration: { returnImmediately: true } })
const v03msg = (text: string) => ({ message: { kind: 'message', messageId: crypto.randomUUID(), role: 'user', parts: [{ kind: 'text', text }] }, configuration: { blocking: false } })
const settle = () => new Promise(r => setTimeout(r, 300))
const idOf = (b: { result?: any }) => b.result?.task?.id ?? b.result?.id

await card('card_v1', '1.0')
await card('card_v03', '0.3')

for (const [v, msg, send, getTask, cancel] of [
  ['v1', v1msg, 'SendMessage', 'GetTask', 'CancelTask'],
  ['v03', v03msg, 'message/send', 'tasks/get', 'tasks/cancel'],
] as const) {
  const version = v === 'v1' ? '1.0' : '0.3'
  const echo = await rpc(`${v}_send_echo`, version, send, msg('hi'))
  await settle()
  await rpc(`${v}_get_completed`, version, getTask, { id: idOf(echo) })

  const slow = await rpc(`${v}_send_slow`, version, send, msg('slow 5 build'))
  await rpc(`${v}_get_working`, version, getTask, { id: idOf(slow) })
  await rpc(`${v}_cancel`, version, cancel, { id: idOf(slow) })

  const ask = await rpc(`${v}_send_ask`, version, send, msg('ask colour'))
  await settle()
  await rpc(`${v}_get_input_required`, version, getTask, { id: idOf(ask) })

  await rpc(`${v}_get_missing`, version, getTask, { id: 'no-such-task' })
}

await worker.close()
const text = JSON.stringify(out, null, 2).replaceAll(worker.url, 'http://worker.test')
writeFileSync(new URL('./fixtures.ts', import.meta.url),
  `// Generated by \`pnpm capture\` from @a2a-js/sdk. Do not edit; re-run instead.\nexport const fixtures = ${text} as const\n`)
console.log(`wrote ${Object.keys(out).length} fixtures`)
