// Generated by `pnpm capture` from @a2a-js/sdk. Do not edit; re-run instead.
export const fixtures = {
  "card_v1": {
    "name": "Fake Worker",
    "description": "Echoes, waits, or asks a question. Test double for a2a-mod.",
    "supportedInterfaces": [
      {
        "url": "http://worker.test/a2a/jsonrpc",
        "protocolBinding": "JSONRPC",
        "tenant": "",
        "protocolVersion": "1.0"
      },
      {
        "url": "http://worker.test/a2a/jsonrpc",
        "protocolBinding": "JSONRPC",
        "tenant": "",
        "protocolVersion": "0.3"
      }
    ],
    "version": "0.1.0",
    "capabilities": {
      "streaming": false,
      "pushNotifications": false,
      "extensions": [],
      "extendedAgentCard": false
    },
    "securitySchemes": {},
    "securityRequirements": [],
    "defaultInputModes": [
      "text"
    ],
    "defaultOutputModes": [
      "text"
    ],
    "skills": [
      {
        "id": "echo",
        "name": "Echo",
        "description": "Replies with the input.",
        "tags": [],
        "examples": [
          "hi"
        ],
        "inputModes": [
          "text"
        ],
        "outputModes": [
          "text"
        ],
        "securityRequirements": []
      },
      {
        "id": "slow",
        "name": "Slow",
        "description": "slow <seconds> <text>: finishes after a delay.",
        "tags": [],
        "examples": [
          "slow 12 build"
        ],
        "inputModes": [
          "text"
        ],
        "outputModes": [
          "text"
        ],
        "securityRequirements": []
      },
      {
        "id": "ask",
        "name": "Ask",
        "description": "ask <thing>: asks a question back first.",
        "tags": [],
        "examples": [
          "ask colour"
        ],
        "inputModes": [
          "text"
        ],
        "outputModes": [
          "text"
        ],
        "securityRequirements": []
      }
    ],
    "signatures": []
  },
  "card_v03": {
    "name": "Fake Worker",
    "description": "Echoes, waits, or asks a question. Test double for a2a-mod.",
    "version": "0.1.0",
    "url": "http://worker.test/a2a/jsonrpc",
    "preferredTransport": "JSONRPC",
    "protocolVersion": "0.3",
    "capabilities": {
      "streaming": false,
      "pushNotifications": false
    },
    "defaultInputModes": [
      "text"
    ],
    "defaultOutputModes": [
      "text"
    ],
    "skills": [
      {
        "id": "echo",
        "name": "Echo",
        "description": "Replies with the input.",
        "tags": [],
        "examples": [
          "hi"
        ],
        "inputModes": [
          "text"
        ],
        "outputModes": [
          "text"
        ]
      },
      {
        "id": "slow",
        "name": "Slow",
        "description": "slow <seconds> <text>: finishes after a delay.",
        "tags": [],
        "examples": [
          "slow 12 build"
        ],
        "inputModes": [
          "text"
        ],
        "outputModes": [
          "text"
        ]
      },
      {
        "id": "ask",
        "name": "Ask",
        "description": "ask <thing>: asks a question back first.",
        "tags": [],
        "examples": [
          "ask colour"
        ],
        "inputModes": [
          "text"
        ],
        "outputModes": [
          "text"
        ]
      }
    ],
    "supportsAuthenticatedExtendedCard": false,
    "supportedInterfaces": [
      {
        "url": "http://worker.test/a2a/jsonrpc",
        "protocolBinding": "JSONRPC",
        "tenant": "",
        "protocolVersion": "1.0"
      },
      {
        "url": "http://worker.test/a2a/jsonrpc",
        "protocolBinding": "JSONRPC",
        "tenant": "",
        "protocolVersion": "0.3"
      }
    ]
  },
  "v1_send_echo": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "task": {
        "id": "252ebe61-f355-4f86-99cd-1146f22860e1",
        "contextId": "e9e0a2f6-d5c2-41e3-b3a6-e2fb303d4325",
        "status": {
          "state": "TASK_STATE_SUBMITTED",
          "timestamp": "2026-10-03T21:50:44.683Z"
        },
        "history": [
          {
            "messageId": "2a9d64ae-a0c7-4256-b9d5-08cc36cc3808",
            "contextId": "e9e0a2f6-d5c2-41e3-b3a6-e2fb303d4325",
            "taskId": "252ebe61-f355-4f86-99cd-1146f22860e1",
            "role": "ROLE_USER",
            "parts": [
              {
                "text": "hi"
              }
            ]
          }
        ]
      }
    }
  },
  "v1_get_completed": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "id": "252ebe61-f355-4f86-99cd-1146f22860e1",
      "contextId": "e9e0a2f6-d5c2-41e3-b3a6-e2fb303d4325",
      "status": {
        "state": "TASK_STATE_COMPLETED",
        "timestamp": "2026-10-03T21:50:44.683Z"
      },
      "artifacts": [
        {
          "artifactId": "c53dba4f-7a78-48bc-8124-eb00981a9b28",
          "name": "result",
          "parts": [
            {
              "text": "echo: hi",
              "mediaType": "text/plain"
            }
          ]
        }
      ],
      "history": [
        {
          "messageId": "2a9d64ae-a0c7-4256-b9d5-08cc36cc3808",
          "contextId": "e9e0a2f6-d5c2-41e3-b3a6-e2fb303d4325",
          "taskId": "252ebe61-f355-4f86-99cd-1146f22860e1",
          "role": "ROLE_USER",
          "parts": [
            {
              "text": "hi"
            }
          ]
        }
      ],
      "metadata": {}
    }
  },
  "v1_send_slow": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "task": {
        "id": "526c3660-821f-4aa2-bef9-56def64350f1",
        "contextId": "acd1e4be-4b74-4ed9-acba-e1480f8312ed",
        "status": {
          "state": "TASK_STATE_SUBMITTED",
          "timestamp": "2026-10-03T21:50:45.009Z"
        },
        "history": [
          {
            "messageId": "d9f95c53-eee9-4e82-8a2c-c614cbc92c4d",
            "contextId": "acd1e4be-4b74-4ed9-acba-e1480f8312ed",
            "taskId": "526c3660-821f-4aa2-bef9-56def64350f1",
            "role": "ROLE_USER",
            "parts": [
              {
                "text": "slow 5 build"
              }
            ]
          }
        ]
      }
    }
  },
  "v1_get_working": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "id": "526c3660-821f-4aa2-bef9-56def64350f1",
      "contextId": "acd1e4be-4b74-4ed9-acba-e1480f8312ed",
      "status": {
        "state": "TASK_STATE_WORKING",
        "timestamp": "2026-10-03T21:50:45.009Z"
      },
      "history": [
        {
          "messageId": "d9f95c53-eee9-4e82-8a2c-c614cbc92c4d",
          "contextId": "acd1e4be-4b74-4ed9-acba-e1480f8312ed",
          "taskId": "526c3660-821f-4aa2-bef9-56def64350f1",
          "role": "ROLE_USER",
          "parts": [
            {
              "text": "slow 5 build"
            }
          ]
        }
      ],
      "metadata": {}
    }
  },
  "v1_cancel": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "id": "526c3660-821f-4aa2-bef9-56def64350f1",
      "contextId": "acd1e4be-4b74-4ed9-acba-e1480f8312ed",
      "status": {
        "state": "TASK_STATE_CANCELED",
        "timestamp": "2026-10-03T21:50:45.018Z"
      },
      "history": [
        {
          "messageId": "d9f95c53-eee9-4e82-8a2c-c614cbc92c4d",
          "contextId": "acd1e4be-4b74-4ed9-acba-e1480f8312ed",
          "taskId": "526c3660-821f-4aa2-bef9-56def64350f1",
          "role": "ROLE_USER",
          "parts": [
            {
              "text": "slow 5 build"
            }
          ]
        }
      ],
      "metadata": {}
    }
  },
  "v1_send_ask": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "task": {
        "id": "6d4c539f-2230-4346-b9be-d1a6dc9a15ba",
        "contextId": "a32a809d-3fc8-4ee1-9057-94419e625d90",
        "status": {
          "state": "TASK_STATE_SUBMITTED",
          "timestamp": "2026-10-03T21:50:45.022Z"
        },
        "history": [
          {
            "messageId": "14b13e5a-b180-4104-9dc3-4e34bd97087c",
            "contextId": "a32a809d-3fc8-4ee1-9057-94419e625d90",
            "taskId": "6d4c539f-2230-4346-b9be-d1a6dc9a15ba",
            "role": "ROLE_USER",
            "parts": [
              {
                "text": "ask colour"
              }
            ]
          }
        ]
      }
    }
  },
  "v1_get_input_required": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "id": "6d4c539f-2230-4346-b9be-d1a6dc9a15ba",
      "contextId": "a32a809d-3fc8-4ee1-9057-94419e625d90",
      "status": {
        "state": "TASK_STATE_INPUT_REQUIRED",
        "message": {
          "messageId": "3ccfa96e-5a9f-44c3-b770-e141c83137ef",
          "contextId": "a32a809d-3fc8-4ee1-9057-94419e625d90",
          "taskId": "6d4c539f-2230-4346-b9be-d1a6dc9a15ba",
          "role": "ROLE_AGENT",
          "parts": [
            {
              "text": "Which colour?",
              "mediaType": "text/plain"
            }
          ],
          "metadata": {}
        },
        "timestamp": "2026-10-03T21:50:45.022Z"
      },
      "history": [
        {
          "messageId": "14b13e5a-b180-4104-9dc3-4e34bd97087c",
          "contextId": "a32a809d-3fc8-4ee1-9057-94419e625d90",
          "taskId": "6d4c539f-2230-4346-b9be-d1a6dc9a15ba",
          "role": "ROLE_USER",
          "parts": [
            {
              "text": "ask colour"
            }
          ]
        },
        {
          "messageId": "3ccfa96e-5a9f-44c3-b770-e141c83137ef",
          "contextId": "a32a809d-3fc8-4ee1-9057-94419e625d90",
          "taskId": "6d4c539f-2230-4346-b9be-d1a6dc9a15ba",
          "role": "ROLE_AGENT",
          "parts": [
            {
              "text": "Which colour?",
              "mediaType": "text/plain"
            }
          ],
          "metadata": {}
        }
      ],
      "metadata": {}
    }
  },
  "v1_get_missing": {
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
      "code": -32001,
      "message": "Task not found: no-such-task",
      "data": [
        {
          "@type": "type.googleapis.com/google.rpc.ErrorInfo",
          "reason": "TASK_NOT_FOUND",
          "domain": "a2a-protocol.org"
        }
      ]
    }
  },
  "v03_send_echo": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "kind": "task",
      "id": "4cb561e4-a44a-4474-855e-962c71757e01",
      "contextId": "395230e3-4a41-45d8-b6db-b1f0f02a9b5f",
      "status": {
        "state": "submitted",
        "timestamp": "2026-10-03T21:50:46.013Z"
      },
      "history": [
        {
          "kind": "message",
          "messageId": "645a5344-00ea-401b-bc63-d8d4036369f0",
          "role": "user",
          "parts": [
            {
              "kind": "text",
              "text": "hi"
            }
          ],
          "contextId": "395230e3-4a41-45d8-b6db-b1f0f02a9b5f",
          "taskId": "4cb561e4-a44a-4474-855e-962c71757e01"
        }
      ]
    }
  },
  "v03_get_completed": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "kind": "task",
      "id": "4cb561e4-a44a-4474-855e-962c71757e01",
      "contextId": "395230e3-4a41-45d8-b6db-b1f0f02a9b5f",
      "status": {
        "state": "completed",
        "timestamp": "2026-10-03T21:50:46.013Z"
      },
      "history": [
        {
          "kind": "message",
          "messageId": "645a5344-00ea-401b-bc63-d8d4036369f0",
          "role": "user",
          "parts": [
            {
              "kind": "text",
              "text": "hi"
            }
          ],
          "contextId": "395230e3-4a41-45d8-b6db-b1f0f02a9b5f",
          "taskId": "4cb561e4-a44a-4474-855e-962c71757e01"
        }
      ],
      "artifacts": [
        {
          "artifactId": "cd31e886-abc0-4393-9620-4b5d512c22fe",
          "parts": [
            {
              "kind": "text",
              "text": "echo: hi"
            }
          ],
          "name": "result"
        }
      ],
      "metadata": {}
    }
  },
  "v03_send_slow": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "kind": "task",
      "id": "f54c5bed-96a4-4a9a-96df-94c0f1fbe1c2",
      "contextId": "7cfda7df-841f-4706-a07d-5b530db71ca4",
      "status": {
        "state": "submitted",
        "timestamp": "2026-10-03T21:50:46.506Z"
      },
      "history": [
        {
          "kind": "message",
          "messageId": "ff4b46ba-1cab-4cdf-be49-be8175e7ccf5",
          "role": "user",
          "parts": [
            {
              "kind": "text",
              "text": "slow 5 build"
            }
          ],
          "contextId": "7cfda7df-841f-4706-a07d-5b530db71ca4",
          "taskId": "f54c5bed-96a4-4a9a-96df-94c0f1fbe1c2"
        }
      ]
    }
  },
  "v03_get_working": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "kind": "task",
      "id": "f54c5bed-96a4-4a9a-96df-94c0f1fbe1c2",
      "contextId": "7cfda7df-841f-4706-a07d-5b530db71ca4",
      "status": {
        "state": "working",
        "timestamp": "2026-10-03T21:50:46.506Z"
      },
      "history": [
        {
          "kind": "message",
          "messageId": "ff4b46ba-1cab-4cdf-be49-be8175e7ccf5",
          "role": "user",
          "parts": [
            {
              "kind": "text",
              "text": "slow 5 build"
            }
          ],
          "contextId": "7cfda7df-841f-4706-a07d-5b530db71ca4",
          "taskId": "f54c5bed-96a4-4a9a-96df-94c0f1fbe1c2"
        }
      ],
      "metadata": {}
    }
  },
  "v03_cancel": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "kind": "task",
      "id": "f54c5bed-96a4-4a9a-96df-94c0f1fbe1c2",
      "contextId": "7cfda7df-841f-4706-a07d-5b530db71ca4",
      "status": {
        "state": "canceled",
        "timestamp": "2026-10-03T21:50:46.512Z"
      },
      "history": [
        {
          "kind": "message",
          "messageId": "ff4b46ba-1cab-4cdf-be49-be8175e7ccf5",
          "role": "user",
          "parts": [
            {
              "kind": "text",
              "text": "slow 5 build"
            }
          ],
          "contextId": "7cfda7df-841f-4706-a07d-5b530db71ca4",
          "taskId": "f54c5bed-96a4-4a9a-96df-94c0f1fbe1c2"
        }
      ],
      "metadata": {}
    }
  },
  "v03_send_ask": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "kind": "task",
      "id": "229b8804-ee7f-40d1-a5cc-a3ee4891ff66",
      "contextId": "e3443de7-8952-487f-98dc-2fee947bfc94",
      "status": {
        "state": "submitted",
        "timestamp": "2026-10-03T21:50:46.514Z"
      },
      "history": [
        {
          "kind": "message",
          "messageId": "83ad1a02-a56f-48e9-bb11-145af93ac374",
          "role": "user",
          "parts": [
            {
              "kind": "text",
              "text": "ask colour"
            }
          ],
          "contextId": "e3443de7-8952-487f-98dc-2fee947bfc94",
          "taskId": "229b8804-ee7f-40d1-a5cc-a3ee4891ff66"
        }
      ]
    }
  },
  "v03_get_input_required": {
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
      "kind": "task",
      "id": "229b8804-ee7f-40d1-a5cc-a3ee4891ff66",
      "contextId": "e3443de7-8952-487f-98dc-2fee947bfc94",
      "status": {
        "state": "input-required",
        "message": {
          "kind": "message",
          "messageId": "5742c539-d8a5-478e-b87d-f710c423ca3f",
          "role": "agent",
          "parts": [
            {
              "kind": "text",
              "text": "Which colour?"
            }
          ],
          "contextId": "e3443de7-8952-487f-98dc-2fee947bfc94",
          "taskId": "229b8804-ee7f-40d1-a5cc-a3ee4891ff66",
          "metadata": {}
        },
        "timestamp": "2026-10-03T21:50:46.514Z"
      },
      "history": [
        {
          "kind": "message",
          "messageId": "83ad1a02-a56f-48e9-bb11-145af93ac374",
          "role": "user",
          "parts": [
            {
              "kind": "text",
              "text": "ask colour"
            }
          ],
          "contextId": "e3443de7-8952-487f-98dc-2fee947bfc94",
          "taskId": "229b8804-ee7f-40d1-a5cc-a3ee4891ff66"
        },
        {
          "kind": "message",
          "messageId": "5742c539-d8a5-478e-b87d-f710c423ca3f",
          "role": "agent",
          "parts": [
            {
              "kind": "text",
              "text": "Which colour?"
            }
          ],
          "contextId": "e3443de7-8952-487f-98dc-2fee947bfc94",
          "taskId": "229b8804-ee7f-40d1-a5cc-a3ee4891ff66",
          "metadata": {}
        }
      ],
      "metadata": {}
    }
  },
  "v03_get_missing": {
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
      "code": -32001,
      "message": "Task not found: no-such-task"
    }
  }
} as const
